tech_conf:
  date_pattern: "%y-%m-%d-%h:%m:%s"
  scheduler_time_minutes: 120
email:
  subject: "nuovi annunci speriamo bene!"
  sender:
    email: "paolo.varie00@gmail.com"
    password: "paolo.varie0027..06..88"
    domain_name: "smtp.gmail.com"
    port: 465
supported_sites_conf :
  - site_name: "immobiliare"
    base_url: ""
    api_case_string: "search-list"
  - site_name: "idealista"
    base_url: "https://www.idealista.it"
searches:
  - title: "zona pietralata (nuova itor)"
    description: ""
    sites:
      - site_name: "immobiliare"
        query_urls:
          - "https://www.immobiliare.it/vendita-case/roma/pietralata/con-piani-intermedi/?criterio=rilevanza&prezzoMassimo=300000&superficieMinima=80"
      - site_name: "idealista"
        query_urls:
          - "https://www.idealista.it/aree/vendita-case/con-prezzo_280000,dimensione_80,piani-intermedi/?shape=%28%28yu%7B%7EFmookAyAs%5EkCsg%40%60%7C%40aVdD%7Er%40yDn%5Cgt%40xL%29%29"
  - title: "ciampino"
    description: ""
    sites:
      - site_name: "immobiliare"
        query_urls:
          - "https://www.immobiliare.it/vendita-case/ciampino/con-piani-intermedi/?criterio=rilevanza&prezzoMassimo=280000"
      - site_name: "idealista"
        query_urls:
          - "https://www.idealista.it/vendita-case/ciampino-roma/con-prezzo_280000,dimensione_80,piani-intermedi/"
  - title: "bracciano e anguillaria"
    description: ""
    sites:
      - site_name: "immobiliare"
        query_urls:
          - "https://www.immobiliare.it/vendita-case/anguillara-sabazia/con-piani-intermedi/?criterio=rilevanza&prezzoMassimo=250000&superficieMinima=80"
          - "https://www.immobiliare.it/vendita-case/bracciano/con-piani-intermedi/?criterio=rilevanza&prezzoMassimo=250000&superficieMinima=80"
      - site_name: "idealista"
        query_urls:
          - "https://www.idealista.it/vendita-case/bracciano-roma/con-prezzo_250000,dimensione_80/"
          - "https://www.idealista.it/vendita-case/anguillara-sabazia-roma/con-prezzo_240000,dimensione_80/"



