conf:
  date_pattern: "%y-%m-%d-%h:%m:%s"
  scheduler_time_minutes: 120
email:
  subject: "nuovi annunci speriamo bene!"
  sender:
    email: "paolo.varie00@gmail.com"
    password: "paolo.varie0027..06..88"
    domain_name: "smtp.gmail.com"
    port: 465
sites:
  -
    site_name: "immobiliare"
    base_url: ""
    query_urls:
      - "https://www.immobiliare.it/vendita-case/roma/"
  -
    site_name: "idealista"
    base_url: "https://www.idealista.it/"
    query_urls:
      - "https://www.idealista.it/aree/vendita-case/?shape=%28%28yvz%7EFqinkAi%60%40kKdAq%5DyB%7BZdCoXrE%7B%40%7CXsDvUrVqWdoA%29%29"

