CONF:
  DATE_PATTERN: "%Y-%m-%d-%H:%M:%S"
EMAIL:
  SUBJECT: "nuovi annunci speriamo bene!"
  SENDER:
    EMAIL: "paolo.varie00@gmail.com"
    PASSWORD: "paolo.varie0027..06..88"
    DOMAIN_NAME: "smtp.gmail.com"
    PORT: 465
SITES:
  -
    SITE_NAME: "IMMOBILIARE"
    BASE_URL: ""
    QUERY_URL:
      - "https://www.immobiliare.it/vendita-case/roma/"
      - ""
  -
    SITE_NAME: "IDEALISTA"
    BASE_URL: "https://www.idealista.it/"
    QUERY_URL:
      - "https://www.idealista.it/"
      - ""

