tech_conf:
  date_pattern: "%y-%m-%d-%h:%m:%s"
  scheduler_time_minutes: 120
email:
  subject: "nuovi annunci speriamo bene!"
  sender:
    email: "paolo.varie00@gmail.com"
    password: "paolo.varie0027..06..88"
    domain_name: "smtp.gmail.com"
    port: 465
db:
  connection_string: "mongodb+srv://buyhomealarm_app_pi:z3jFXk69sdD8AZf@cluster0.48mwk.mongodb.net/buyhomealarm_db?retryWrites=true&w=majority"
supported_sites_conf :
  - site_name: "immobiliare"
    base_url: ""
    api_case_string: "search-list"
  - site_name: "idealista"
    base_url: "https://www.idealista.it"
telegram:
  bot:
    api_token: "5138319576:AAE0Blx0DTpEvgHCmezgENqexbaC2HkMFAI"