IMMOBILIARE_SITE_NAME = "IMMOBILIARE"
IMMOBILIARE_URL = "https://www.immobiliare.it/vendita-case/roma/"
IDEALISTA_SITE_NAME = "IDEALISTA"
IDEALISTA_URL = "https://www.idealista.it/aree/vendita-case/?shape=%28%28%7Dom%7EFsgpjAyqGa%7B%40enJdPihBquEmkB%7DlPjnEghNdnIgqEpqPhoFdrBtqGeB%60iGkuAxwQ_rG%7EcC%29%29"
IDEALISTA_BASE_URL = "https://www.idealista.it/"