DEFAULT_ENV = "dev"
ENV_ENVIROMENT_ENV = "BUYHOMEALARM_ENV"
ENV_ENVIROMENT_PROD_VALUE = "prod"
ENV_ENVIROMENT_DEV_VALUE = "dev"
CONFIG_FILE_DEV_NAME = "../config/config_dev.yml"
CONFIG_FILE_PROD_NAME = "../config/config_prod.yml"

# SUPPORTED ACTION TYPE
ACTION_TYPE_SEARCH_HOME = "SEARCH_HOME"

# SUPPORTED SITE
IMMOBILIARE_SITE_NAME = "IMMOBILIARE"
IDEALISTA_SITE_NAME = "IDEALISTA"
CASA_IT_SITE_NAME = "CASA_IT"
